info: "OpenAIRE Matomo Tracker"

Matomo_Parameters:
  #Matomo tracker Endpoint
  matomo_url: "https://analytics.openaire.eu/"
  #Repository Base Url
  repository_base_url: "https://repository.com"
  #Matomo Repository Site ID
  idSite: 1
  #Matomo authenticastion token
  token_auth: "12345"
  #matomo parameters (default values)
  delay_after_failure: 10
  default_max_attempts: 3
  default_socket_timeout: 300
  ip_anonymization: false

  #Skip the n first lines to start parsing/importing data at a given line for the specified log file
  skip_lines: 0

  # Number of recorders. It should be set to the number of CPU cores in your server.
  # You can also experiment with higher values which may increase performance until a certain point
  recorders: 1
  
  #OAI-PMH Configuration
  oaipmh_preamble: "oai:repository.site:"
  
  #Metadata Location (supports multiple locations and regular expressions)
  tracking_metadata:
  - "/([0-9]*)/(?!pdf)$"
  
  #Item Location (supports multiple locations and regular expressions)
  tracking_download:
  - "/([0-9]*)/[0-9]*\\w.*pdf"
