info: "OpenAIRE Matomo Tracker"

Matomo_Parameters:
  #Matomo tracker Endpoint
  matomo_url: "https://analytics.openaire.eu/"
  #Repository Base Url
  repository_base_url: "http://localhost"
  #Matomo Repository Site ID
  idSite: 1
  #Matomo authenticastion token 
  token_auth: "123456789"
  #matomo parameters (default values)
  delay_after_failure: 10
  default_max_attempts: 3
  default_socket_timeout: 300
  ip_anonymization: true

  # Number of recorders. It should be set to the number of CPU cores in your server.
  # You can also experiment with higher values which may increase performance until a certain point
  recorders: 1
  #OAI-PMH Configuration
  oaipmh_preamble: "oai:abc.def"
  #Metadata Location (regexp supported)
  tracking_metadata:
  #- "/[0-9]*"
  #- "^((?!.*pdf.*).)*$"
  #- "/handle/[0-9]*"
  - "/record"
  - "/publication/"
  #Item Location (regexp supported)
  tracking_download:
   #- "pdf"
  #- "/[0-9]*"
  #- "/bitstream/handle/[0-9]*"
    - "/download"



